'use client';
import { useEffect, useRef, useState } from 'react';
import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
import { Maximize2, Camera, LoaderCircle, Box } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Panel, fileUrl } from './types';
import { SoftwareRenderer } from './SoftwareRenderer';
import {createBendOverlay,hingeTransforms,effectiveFraction,hingePoint,bendLabel,vector as v} from './BendOverlay';
import type {Drawing,Hinge} from './BendOverlay';
type Props={panels:Panel[];fraction:number;gap:number;alignment:string;paint:boolean;wire:boolean;bendLines:boolean;view:string;onHover:(value:string|null)=>void};
function animatedModel(data:Drawing,panelId:string){
 const group=new THREE.Group();group.scale.setScalar(.001);const plates=new Map<number,THREE.Group>();const bends=new Map<number,THREE.Mesh>();
 const finish=new THREE.MeshStandardMaterial({color:0x39a88e,metalness:.18,roughness:.62,side:THREE.DoubleSide});const metal=new THREE.MeshStandardMaterial({color:0xb5c1c4,metalness:.55,roughness:.55});
 for(const face of data.faces){const body=new THREE.Group();body.matrixAutoUpdate=false;for(const poly of face.polygons){const shape=new THREE.Shape(poly.outer.map(q=>new THREE.Vector2(q[0],q[1])));for(const h of poly.holes)shape.holes.push(new THREE.Path(h.map(q=>new THREE.Vector2(q[0],q[1]))));const geom=new THREE.ExtrudeGeometry(shape,{depth:data.thickness,bevelEnabled:false});geom.translate(0,0,-data.thickness/2);body.add(new THREE.Mesh(geom,[finish,metal]));}plates.set(face.id,body);group.add(body)}
 for(const e of data.bends){if(data.mode==='flat_review'||e.angle==null)continue;const mesh=new THREE.Mesh(new THREE.BufferGeometry(),finish);mesh.userData={hinge:e,panelId};bends.set(e.id,mesh);group.add(mesh)}
 function update(fraction:number){
  fraction=effectiveFraction(data,fraction);const transforms=hingeTransforms(data,fraction);const world=(id:number)=>transforms.get(id)!;
  for(const [id,plate]of plates)plate.matrix.copy(world(id));
  for(const e of data.bends){const mesh=bends.get(e.id);if(!mesh)continue;const axis=v(e.axis),d=v(e.d),h=hingePoint(e),allowance=e.allowance??data.allowance;const angle=THREE.MathUtils.degToRad(e.angle??0)*fraction;let geom:THREE.BufferGeometry;
   if(fraction<.00001){geom=new THREE.BoxGeometry(e.high-e.low,allowance,data.thickness);geom.rotateZ(Math.atan2(axis.y,axis.x));const c=h.clone().addScaledVector(axis,(e.low+e.high)/2);geom.translate(c.x,c.y,c.z)}
   else{const segments=24;const inner=allowance/Math.abs(angle)-data.k_factor*data.thickness;const rm=inner+data.thickness/2;const w=new THREE.Vector3().crossVectors(axis,d).multiplyScalar(Math.sign(angle));const center=h.clone().addScaledVector(d,-allowance/2).addScaledVector(w,rm);const positions:number[]=[];const index:number[]=[];
    for(const length of [e.low,e.high])for(const radius of [inner,inner+data.thickness])for(let k=0;k<=segments;k++){const p=center.clone().addScaledVector(axis,length).addScaledVector(w.clone().applyAxisAngle(axis,angle*k/segments),-radius);positions.push(p.x,p.y,p.z)}
    const n=segments+1;const quad=(a:number,b:number,c:number,d:number)=>index.push(a,b,c,a,c,d);
    for(let k=0;k<segments;k++){quad(k,k+1,2*n+k+1,2*n+k);quad(n+k,3*n+k,3*n+k+1,n+k+1);quad(k,n+k,n+k+1,k+1);quad(2*n+k,2*n+k+1,3*n+k+1,3*n+k)}quad(0,2*n,3*n,n);quad(segments,n+segments,3*n+segments,2*n+segments);
    geom=new THREE.BufferGeometry();geom.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));geom.setIndex(index);geom.computeVertexNormals();
   }mesh.geometry.dispose();mesh.geometry=geom;mesh.matrixAutoUpdate=false;mesh.matrix.copy(world(e.parent));
  }
 }
 update(0);return {group,update};
}
export default function ModelViewer(props:Props){
 const host=useRef<HTMLDivElement>(null);const ref=useRef<{fit:()=>void;screenshot:()=>void;apply:(p:Props)=>void}|null>(null);const latest=useRef(props);latest.current=props;const [state,setState]=useState('Loading solid geometry…');const [error,setError]=useState(false);const [software,setSoftware]=useState(false);
 const ids=props.panels.map(p=>p.id+':'+p.revision).join('|');
 useEffect(()=>{let alive=true;let frame=0;const root=host.current!;setState('Loading solid geometry…');setError(false);let renderer:THREE.WebGLRenderer|SoftwareRenderer;
  try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,preserveDrawingBuffer:true})}catch{renderer=new SoftwareRenderer();setSoftware(true)}
  renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0xeef3f3);renderer.outputColorSpace=THREE.SRGBColorSpace;root.appendChild(renderer.domElement);
  const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(32,1,.001,1000);camera.up.set(0,0,1);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.1;
  scene.add(new THREE.HemisphereLight(0xffffff,0x82999d,2.1));const sun=new THREE.DirectionalLight(0xffffff,3);sun.position.set(3,-3,5);scene.add(sun);const fill=new THREE.DirectionalLight(0xc5e5e7,1.3);fill.position.set(-2,2,-4);scene.add(fill);
  const grid=new THREE.GridHelper(20,100,0xc1d1d1,0xd8e2e2);grid.rotation.x=Math.PI/2;scene.add(grid);
  const items:{root:THREE.Group;final:THREE.Group;animated:ReturnType<typeof animatedModel>;data:Drawing;panel:Panel;bounds:THREE.Box3;overlay:ReturnType<typeof createBendOverlay>}[]=[];
  function layout(){let x=0;const p=latest.current;for(const item of items){const box=item.bounds;const size=box.getSize(new THREE.Vector3());item.root.position.set(x-box.min.x,p.alignment==='near'?-box.min.y:p.alignment==='far'?-box.max.y:-(box.min.y+box.max.y)/2,-box.min.z);x+=size.x+p.gap/1000}grid.position.z=-.012;}
  function fit(){if(!items.length)return;const box=new THREE.Box3();for(const item of items){item.root.updateMatrixWorld(true);box.union(new THREE.Box3().setFromObject(item.final.visible?item.final:item.animated.group))}const size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3());const vertical=THREE.MathUtils.degToRad(camera.fov),horizontal=2*Math.atan(Math.tan(vertical/2)*camera.aspect);const dist=(size.length()/2)/Math.sin(Math.min(vertical,horizontal)/2)*1.12+.1;const type=latest.current.view;const direction=type==='top'?new THREE.Vector3(0,0,1):type==='front'?new THREE.Vector3(0,-1,.001):type==='side'?new THREE.Vector3(1,0,.001):new THREE.Vector3(1,-1.25,1.15).normalize();camera.position.copy(center).addScaledVector(direction,dist);controls.target.copy(center);camera.near=.001;camera.far=Math.max(100,dist*20);camera.updateProjectionMatrix();controls.update()}
  function apply(p:Props){for(const item of items){item.final.visible=p.fraction>=.99999&&item.panel.artifacts.includes('panel.glb');item.overlay.group.visible=p.bendLines;item.overlay.update(p.fraction);item.animated.group.visible=!item.final.visible;if(item.animated.group.visible)item.animated.update(p.fraction);item.final.traverse(o=>{if(o instanceof THREE.Mesh){const mats=Array.isArray(o.material)?o.material:[o.material];for(const mat of mats){if('wireframe'in mat)mat.wireframe=p.wire;if(mat instanceof THREE.MeshStandardMaterial&&o.name.includes('_paint'))mat.color.set(p.paint?0x39a58e:0xb7c5c7)}}});item.animated.group.traverse(o=>{if(o instanceof THREE.Mesh){for(const mat of Array.isArray(o.material)?o.material:[o.material]){if('wireframe'in mat)mat.wireframe=p.wire;if(mat instanceof THREE.MeshStandardMaterial)mat.color.set(p.paint?0x39a58e:0xb7c5c7)}}})}layout()}
  ref.current={fit,apply,screenshot:()=>{renderer.render(scene,camera);const a=document.createElement('a');a.href=renderer.domElement.toDataURL('image/png');a.download='FlatForge_3D_view.png';a.click()}};
  const loader=new GLTFLoader();Promise.all(props.panels.map(async panel=>{const [gltf,response]=await Promise.all([panel.artifacts.includes('panel.glb')?loader.loadAsync(fileUrl(panel,'panel.glb')):Promise.resolve(null),fetch(fileUrl(panel,'viewer.json'))]);if(!response.ok)throw new Error('Viewer metadata unavailable');const data=await response.json() as Drawing;if(!alive)return;const object=new THREE.Group();const final=gltf?.scene??new THREE.Group();const animated=animatedModel(data,panel.id);const bounds=new THREE.Box3().setFromObject(gltf?final:animated.group);const overlay=createBendOverlay(data,panel.id);final.traverse(o=>{o.userData.panelId=panel.id});object.add(final,animated.group,overlay.group);scene.add(object);items.push({root:object,final,animated,data,panel,bounds,overlay})})).then(()=>{if(!alive)return;items.sort((a,b)=>props.panels.findIndex(p=>p.id===a.panel.id)-props.panels.findIndex(p=>p.id===b.panel.id));apply(latest.current);fit();setState('')}).catch(()=>{if(alive){setState('Unable to load the 3D result. Retry or download the STEP file.');setError(true)}});
  const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();ray.params.Line.threshold=.004;const move=(event:PointerEvent)=>{const rect=renderer.domElement.getBoundingClientRect();mouse.set((event.clientX-rect.left)/rect.width*2-1,-(event.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(mouse,camera);const targets=items.flatMap(i=>[i.final.visible?i.final:i.animated.group,...(i.overlay.group.visible?[i.overlay.group]:[])]);const hits=ray.intersectObjects(targets,true);let message:string|null=null;if(hits.length){const object=(hits.find(h=>h.object.userData.bendOverlay)??hits[0]).object;const match=object.name.match(/bend_(\d+)/);const item=items.find(i=>i.panel.id===object.userData.panelId);const hinge=object.userData.hinge as Hinge|undefined;const e=hinge??(match&&item?item.data.bends.find(b=>b.id===Number(match[1])):undefined);if(e)message=bendLabel(e);}latest.current.onHover(message)};
  renderer.domElement.addEventListener('pointermove',move);renderer.domElement.addEventListener('pointerleave',()=>latest.current.onHover(null));
  const resize=new ResizeObserver(()=>{const w=root.clientWidth,h=root.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()});resize.observe(root);
  function loop(){frame=requestAnimationFrame(loop);controls.update();renderer.render(scene,camera)}loop();
  return()=>{alive=false;cancelAnimationFrame(frame);resize.disconnect();controls.dispose();for(const item of items)item.overlay.dispose();scene.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();for(const mat of Array.isArray(o.material)?o.material:[o.material])mat.dispose()}});renderer.dispose();renderer.domElement.remove();ref.current=null};
 // Geometry changes require a fresh scene, presentation changes do not.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[ids]);
 useEffect(()=>{ref.current?.apply(props)},[props.fraction,props.paint,props.wire,props.bendLines,props.gap,props.alignment]);
 useEffect(()=>{ref.current?.fit()},[props.view,props.gap,props.alignment]);
 return <div className="viewer-stage"><div ref={host} className="webgl-host"/>{state&&<div className="viewer-loading">{error?<Box/>:<LoaderCircle className="spin"/>}<span>{state}</span></div>}<div className="viewport-actions"><Button variant="outline" size="icon" aria-label="Fit model to view" onClick={()=>ref.current?.fit()}><Maximize2/></Button><Button variant="outline" size="icon" aria-label="Download viewport PNG" onClick={()=>ref.current?.screenshot()}><Camera/></Button></div><div className="axis-key"><span className="x">X</span><span className="y">Y</span><span className="z">Z</span><small>mm</small></div><div className="viewport-help">{props.panels.some(p=>!p.artifacts.includes('panel.glb'))&&<>Unresolved folds · flat review preview · </>}{software&&<>Software preview · </>}Drag to orbit <span>·</span> Right-drag to pan <span>·</span> Scroll to zoom</div></div>
}
