export type Settings={thickness:number;radius:number;deduction:number;input_type:'flat_pattern'|'folded_dimensions'};
export type Face='+X'|'-X'|'+Y'|'-Y'|'+Z'|'-Z';
export type AssemblyEntry={id:string;panelId:string;myFace:Face;targetId:string|null;targetFace:Face|null;gap:number};
export type Bend={id:number;bend_ids:string[];parent:number;child:number;angle:number|null;key:string;confirmed?:boolean;direction?:'up'|'down'|null;detected_direction?:'up'|'down'|null;source_angle?:number|null;drawing_dimensions?:{handle:string;value_deg:number|null;convention:string;status:string}[];source:{profile:string;vertex?:number;angle:number}[]};
export type SectionDiagnostic={max_strip_error_mm:number;normal_to_all_hinges:boolean;turn_angles_deg?:number[];segment_checks?:{segment:number;face:number;source_handles:string[];observed_flat_mm:number;required_flat_mm:number;residual_mm:number;within_tolerance:boolean}[]};
export type Panel={id:string;project_id:string;filename:string;status:string;settings:Settings;overrides:Record<string,unknown>;report:{verification?:{status:string;physical_unfolding?:string;validation_mode?:string};warnings?:{code:string;message:string}[];panel_bend_angle?:{value:number|null;values:number[];status:'MULTIPLE'|'DETECTED'|'MISSING';manual_value:number|null;unresolved:number;convention:'included';message:string};angle_review?:{policy:string;evidence_checked:boolean;detected:number;manual:number;unresolved:number;fallback_magnitude_deg:number;fallback_requires_confirmation:boolean;message:string};angular_annotations?:{handle:string;value_deg:number|null;status:string;profile?:string;vertex?:number;convention?:string;rotation_magnitude_deg?:number|null;reason:string}[];corner_angle_candidates?:{key:string;bend_ids:string[];section_rotation_deg:number;candidate_rotation_deg:number;candidate_included_angle_deg:number;adjacent_face:number;requires_confirmation:boolean;reason:string}[];strip_tolerance_mm?:number;review_catalog?:import('./GeometryReview').SectionReview[];review_geometry?:import('./GeometryReview').GeometryEvidence;review_model?:{status:string;file:string;message:string};flat_width?:number;flat_height?:number;bbox?:number[];bend_lines?:number;physical_bends?:number;faces?:number;settings?:Settings;layers?:Record<string,number>;section_convention?:{layer:string|null;alias_used:boolean};bends?:Bend[];issues?:{code:string;message:string;field?:string;suggested?:number}[];unresolved_bends?:{key:string;bend_ids:string[];parent:number;child:number;axis:string;reason:string}[];section_checks?:{validation_scope?:string;profile:string;chain_status:string;full_plane_status:string;max_length_error_mm:number|null;max_turn_error_deg:number|null}[];thickness_evidence?:{value:number|null;confidence:string};deduction_evidence?:{value:number|null;confidence:string};input_evidence?:{classification:string;reason:string};section_mapping?:{profile:string;cut_axis?:string;coordinate?:number;method?:string;status?:string;reason?:string;candidate_chains?:number;max_strip_error_mm?:number;nearest_candidate?:SectionDiagnostic|null;nearest_normal_candidate?:SectionDiagnostic|null;nearest_projected_candidate?:SectionDiagnostic|null}[];unfold_check?:{symmetric_difference_percent:number;status:string};conversion?:{status:string};phase_message?:string;error?:string};artifacts:string[];error:string;manual_value:number|null;manual_axis:string;created:number;updated:number;revision:number;sample?:boolean;asset_base?:string};
export type Project={id:string;name:string;client:string;created:number};
export type Bootstrap={mode:'sample'|'live';settings:Settings;projects:Project[];panels:Panel[];service_message?:string;capabilities:{connected:boolean;worker_online:boolean;dwg:boolean;max_upload_mb:number;exports?:string[]}};
export const fileUrl=(p:Panel,name:string)=>p.sample?`${p.asset_base}/${name}`:`/api/engine/panels/${p.id}/files/${encodeURIComponent(name)}`;
export async function api<T=Record<string,unknown>>(path:string,body?:unknown,method='POST'):Promise<T>{
 const form=body instanceof FormData;const r=await fetch('/api/engine'+path,{method,headers:form?undefined:{'content-type':'application/json'},body:body===undefined?undefined:form?body:JSON.stringify(body)});
 if(!r.ok){let data:{detail:unknown};try{data=await r.json() as {detail:unknown}}catch{data={detail:'Request failed'}}throw new Error(typeof data.detail==='string'?data.detail:JSON.stringify(data.detail))}return r.json() as Promise<T>;
}
