export type Settings={thickness:number;radius:number;deduction:number;input_type:'flat_pattern'|'folded_dimensions'};
export type Face='+X'|'-X'|'+Y'|'-Y'|'+Z'|'-Z';
export type AssemblyEntry={id:string;panelId:string;myFace:Face;targetId:string|null;targetFace:Face|null;gap:number};
export type Bend={id:number;bend_ids:string[];parent:number;child:number;angle:number|null;key:string;confirmed?:boolean;source:{profile:string;vertex?:number;angle:number}[]};
export type Panel={id:string;project_id:string;filename:string;status:string;settings:Settings;overrides:Record<string,unknown>;report:{flat_width?:number;flat_height?:number;bbox?:number[];bend_lines?:number;physical_bends?:number;faces?:number;settings?:Settings;layers?:Record<string,number>;bends?:Bend[];issues?:{code:string;message:string;field?:string;suggested?:number}[];unresolved_bends?:{key:string;bend_ids:string[];parent:number;child:number;axis:string;reason:string}[];section_checks?:{profile:string;chain_status:string;full_plane_status:string;max_length_error_mm:number;max_turn_error_deg:number}[];thickness_evidence?:{value:number|null;confidence:string};deduction_evidence?:{value:number|null;confidence:string};input_evidence?:{classification:string;reason:string};section_mapping?:{profile:string;cut_axis:string;coordinate:number;method:string}[];unfold_check?:{symmetric_difference_percent:number;status:string};conversion?:{status:string};phase_message?:string;error?:string};artifacts:string[];error:string;manual_value:number|null;manual_axis:string;created:number;updated:number;revision:number;sample?:boolean;asset_base?:string};
export type Project={id:string;name:string;client:string;created:number};
export type Bootstrap={mode:'sample'|'live';settings:Settings;projects:Project[];panels:Panel[];service_message?:string;capabilities:{connected:boolean;worker_online:boolean;dwg:boolean;max_upload_mb:number;exports?:string[]}};
export const fileUrl=(p:Panel,name:string)=>p.sample?`${p.asset_base}/${name}`:`/api/engine/panels/${p.id}/files/${encodeURIComponent(name)}`;
export async function api<T=Record<string,unknown>>(path:string,body?:unknown,method='POST'):Promise<T>{
 const form=body instanceof FormData;const r=await fetch('/api/engine'+path,{method,headers:form?undefined:{'content-type':'application/json'},body:body===undefined?undefined:form?body:JSON.stringify(body)});
 if(!r.ok){let data:{detail:unknown};try{data=await r.json() as {detail:unknown}}catch{data={detail:'Request failed'}}throw new Error(typeof data.detail==='string'?data.detail:JSON.stringify(data.detail))}return r.json() as Promise<T>;
}
